platform :ios, 	:deployment_target => "6.0"
pod 'Reachability',      '~> 2.0.4'
pod 'OpenUDID',     	 '~> 1.0.0'
pod 'LRResty',     	 '~> 0.11.0'
pod 'NSLogger',   	 '~> 1.1'
pod 'SDWebImage', 	 '~> 2.6'
pod 'ShareKit/Facebook',  '~> 2.0'
pod 'BlockAlertsAnd-ActionSheets',          '~> 1.0.0'
pod 'iRate',		  '~> 1.4.7'
pod 'DejalActivityView',     '~> 1.1'
pod 'UrbanAirship-iOS-SDK', '~> 1.4.0'
pod 'LAWalkthrough'
